### ISSUE TITLE
Reusing DNS names not working

### ISSUE THREAD

**Issue by SvenS13** [gardener/gardener-extension-shoot-dns-service#242]
**How to categorize this issue?**
/area cleanup
/kind bug

**What happened**:
After deleting an Nginx ingress controller from our Kyma cluster, the dns names referenced in the "dns.gardener.cloud/dnsnames" annotation before, can not be used by other ingresses. It seems that the cluster gets into a messy state. If I want to reach the hostname, I get an 404 response.

**What you expected to happen**:
I expect the dns names to be cleaned up and I can reuse the host names in other ingresses.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Nginx ingress controller (https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.0/deploy/static/provider/cloud/deploy.yaml) and add the service annotations "dns.gardener.cloud/dnsnames: $HOST_NAME". After that, delete the Nginx ingress controller again and try to re-use $HOST_NAME.

**Environment**:
Kyma

- Kubernetes version (use `kubectl version`): v1.26.7

**Comment by MartinWeindel** [comment]
Cannot reproduce the issue. After deleting the NGINX ingress controller (and its service) the DNS record sets are cleaned up as expected, i.e. the domain name can be reused.

@SvenS13 Please try to reproduce it yourself and provide more details and logs about it.

**Comment by MartinWeindel** [comment]
The DNS records are removed as soon as the service (or at least its annotations) are removed. You may check the events of the service. It may fail if the corresponding DNSProvider is not ready (e.g. the credentials are not valid anymore).
If you are a SAP employee, you may provide me the Gardener dashboard URL of your cluster by Slack or Teams, so that I can take a look.
